# Generated by Django 3.2.9 on 2024-08-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('work_name', models.CharField(max_length=50)),
                ('tag', models.TextField()),
                ('summry', models.TextField()),
            ],
        ),
    ]
