# Generated by Django 3.2.9 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='linked',
            field=models.TextField(default='link', verbose_name='link'),
            preserve_default=False,
        ),
    ]
