# Generated by Django 5.1 on 2024-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_novel", "0002_novel_linked"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="word_num",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="linked",
            field=models.TextField(),
        ),
    ]
